stacks:
  - name: sber
    provider: sbercloud
    accessKey: <%= env.SBER_ACCESS_KEY %>
    secretKey: <%= env.SBER_SECRET_KEY %>
    projectId: <%= env.SBER_PROJECT_ID %>
    ## backend
    backendConfiguration:
      bucket: <%= env.SBER_STATE_BUCKET_NAME %>
      accessKey: <%= env.SBER_ACCESS_KEY %>
      secretKey: <%= env.SBER_SECRET_KEY %>

    ## iam users
    iamUsers: []

    ## regestries
    registries: []

    ## buckets
    buckets: []

    ## keypairs
    keyPairs: []

    ## elasticIp
    staticIpConfig:
      shareBandwidths: []
      staticIps: []

    ## vpcs
    vpcs: []

    ## secgroups
    secGroups: []

    ## postgres
    pgClusters: []

    ## k8s
    k8sClusters: []


  - name: yandex
    cloudId: <%= env.YC_CLOUD_ID %>
    token: <%= env.YC_TOKEN %>
    folderId: <%= env.YC_FOLDER_ID %>
    provider: yandex

    ## backend
    backendConfiguration:
      bucket: <%= env.YC_STATE_BUCKET_NAME %>
      accessKey: <%= env.YC_ACCESS_KEY %>
      secretKey: <%= env.YC_SECRET_KEY %>

    ## service accounts
    serviceAccounts: []

    ## kmsKeys
    kmsKeys: []

    ## lockbox
    lockboxSecrets: []

    ## buckets
    buckets: []

    ## static ips
    staticIps: []

    ## network
    vpcs: []

    ## private vms
    privateInstances: []

    ## public vms
    publicInstances: []

    ## instance groups
    instanceGroups: []

    ## registries
    registries: []

    ## k8s
    k8sClusters: []

    ## postgres
    pgClusters: []

    ## mysql
    mysqlClusters: []

    ## elastic search
    elasticSearchClusters: []

    # mongo
    mongoClusters: []

    ## clickhouse
    clickHouseClusters: []

    ## redis
    redisClusters: []

    ## network load balancers
    networkLoadBalancers: []