stacks:
  - name: production
    cloudId:
    token: <%= env.YC_TOKEN %>
    folderId:
    provider: yandex

    ## backend
    backendConfiguration:
      bucket:
      accessKey: <%= env.ACCESS_KEY %>
      secretKey: <%= env.SECRET_KEY %>

    ## service accounts
    serviceAccounts: []

    ## kmsKeys
    kmsKeys: []

    ## lockbox
    lockboxSecrets: []

    ## buckets
    buckets: []

    ## static ips
    staticIps: []

    ## network
    vpcs: []

    ## private vms
    privateInstances: []

    ## public vms
    publicInstances: []

    ## registries
    registries: []

    ## k8s
    k8sClusters: []

    ## postgres
    pgClusters: []

    ## mysql
    mysqlClusters: []

    ## elastic search
    elasticSearchClusters: []

    # mongo
    mongoClusters: []

    ## clickhouse
    clickHouseClusters: []

    ## redis
    redisClusters: []