stacks:
  - name: production
    cloudId:
    token: <%= env.YC_TOKEN %>
    folderId:
    provider: yandex

    ## backend
    backendConfiguration:
      bucket:
      accessKey: <%= env.ACCESS_KEY %>
      secretKey: <%= env.SECRET_KEY %>

    serviceAccounts: []