apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <name_of_your_external_secret>
  namespace: <name_of_namespace>
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: <name_of_cluster_secret_store>
    kind: ClusterSecretStore
  target:
    name: my-prod-secret
  dataFrom:
    - extract:
        key: <id_of_lockbox_secret>